---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app }}-loader-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    app.kubernetes.io/name: {{ include "rag-lsd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
data:
  EMBEDDING_MODEL: "{{ .Values.lsdEmbeddingModel }}"
  EMBEDDING_DIMENSION: {{ .Values.lsdEmbeddingDimension | toString | quote }}
  EMBEDDING_MODEL_PROVIDER: "{{ .Values.lsdEmbeddingModelProvider }}"
  LLAMA_STACK_HOST: "{{ .Values.app }}-service"
  LLAMA_STACK_PORT: {{ .Values.lsdPort | toString | quote }}
  LLAMA_STACK_SECURE: "False"
  DOCS_FOLDER: "{{ .Values.docsFolder }}"
  CHUNK_SIZE_IN_TOKENS: "{{ .Values.lsdChunkSizeInTokens }}"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.app }}-loader-{{ randAlphaNum 5 | lower }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    app.kubernetes.io/name: {{ include "rag-lsd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/component: loader
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        app.kubernetes.io/name: {{ include "rag-lsd.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: {{ .Values.partOf }}
        app.kubernetes.io/component: loader
    spec:
      restartPolicy: Never
      initContainers:
      - name: deterministic-delay-and-health-check
        image: curlimages/curl:8.5.0
        command: ['sh', '-c']
        args:
          - |
            set -e
            
            # Try to reach /docs with LLAMA_STACK_HOST and LLAMA_STACK_PORT for MAX_RETRIES times and sleep DELAY seconds between each try
            MAX_RETRIES={{ .Values.loaderJobRetries | default 10 }}
            DELAY={{ .Values.loaderDelay | default 5 | toString | quote }}
            HEALTH_CHECK_URL=http://{{ .Values.app }}-service:{{ .Values.lsdPort }}/docs
            for i in $(seq 1 ${MAX_RETRIES}); do
              if curl -f $HEALTH_CHECK_URL; then
                break
              fi
              sleep ${DELAY}
            done
            if [ $i -eq ${MAX_RETRIES} ]; then
              echo "Failed to reach /docs after ${MAX_RETRIES} tries"
              exit 1
            fi
        envFrom:
        - configMapRef:
            name: {{ .Values.app }}-loader-config
      containers:
      - name: loader
        image: "{{ .Values.loaderImage }}"
        imagePullPolicy: Always
        args:
        - --delay
        - {{ .Values.loaderDelay | default 0 | toString | quote }}
        envFrom:
        - configMapRef:
            name: {{ .Values.app }}-loader-config
        volumeMounts:
        - name: docs-volume
          mountPath: "{{ .Values.docsFolder }}"
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
      volumes:
      - name: docs-volume
        configMap:
          name: {{ .Values.app }}-documents
  backoffLimit: {{ .Values.loaderJobRetries | default 3 }}