---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MILVUS_DB_PATH: {{ .Values.milvusDbPath }}
  FMS_ORCHESTRATOR_URL: {{ .Values.fmsOchestratorUrl }}
{{- range .Values.models }}
  {{ include "rag-lsd.envVarName" .name }}_URL: "{{ "http://" }}{{ .name }}-predictor:8080/v1"
  {{ include "rag-lsd.envVarName" .name }}_MODEL: "{{ .name }}"
{{- if .api_key }}
  {{ include "rag-lsd.envVarName" .name }}_API_KEY: "{{ .api_key }}"
{{- end }}
{{- if .tlsVerify }}
  {{ include "rag-lsd.envVarName" .name }}_TLS_VERIFY: "{{ .tlsVerify }}"
{{- end }}
{{- if .maxTokens }}
  {{ include "rag-lsd.envVarName" .name }}_MAX_TOKENS: "{{ .maxTokens }}"
{{- end }}
{{- end }}